apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: wxycbrn2e-python 
  janus-idp.io/tekton: wxycbrn2e-python
  backstage.io/kubernetes-id: wxycbrn2e-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: wxycbrn2e-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml