apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: wxycbrn2e-python
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: rhtap-quay-quay-rhtap-quay.apps.clusterpool-sdp9s.rhtap.devcluster.openshift.com/rhtap/rhtap-qe-python:25c310e996f159f455d079b5c18226caca3f400b@sha256:419b6c95689d3ed1a94ffce19cda88ea9a85893fc9105b26d9681d376aab9e8e
          name: container-image
